# Generated by Django 5.0.6 on 2024-07-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('data', models.TextField(blank=True, null=True)),
                ('matched_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fingerprint.audiovideofile')),
            ],
        ),
    ]
