# Generated by Django 5.0.6 on 2024-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endpointusage',
            index=models.Index(fields=['timestamp'], name='analytics_e_timesta_f733a9_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointusage',
            index=models.Index(fields=['endpoint'], name='analytics_e_endpoin_6ae31f_idx'),
        ),
    ]
