# Generated by Django 5.0.6 on 2024-05-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255, null=True)),
                ('duration_seconds', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=255)),
                ('start_time_seconds', models.FloatField()),
                ('audio_video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprint.audiovideofile')),
            ],
            options={
                'unique_together': {('audio_video_file', 'hash_value', 'start_time_seconds')},
            },
        ),
    ]
