# Generated by Django 5.0.6 on 2024-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenthash',
            name='codec_type',
            field=models.CharField(default='audio', max_length=10),
        ),
    ]
