# Generated by Django 5.0.6 on 2024-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenthash',
            name='hash_value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
