# Generated by Django 5.0.6 on 2024-07-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0002_endpointusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndpointUsage',
        ),
    ]
